spring.application.name=Springboot-API-VENTAS
server.port=8080
spring.datasource.url=jdbc:mysql://rushley-db.ceplguzwspve.us-east-1.rds.amazonaws.com:3306/ventasdb?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=admin
spring.datasource.password=rushley77
spring.datasource.platform=mysql
spring.jpa.database=mysql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect